version: '2.4'
services:
  haproxy:
    image: asn/haproxy 
    build: haproxy/
    ports:
      - "80:80"
    volumes:
      # HAProxy static config file
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

#  nginx:
#    image: asn/nginx
#    build: nginx/
#    ports:
#      - "80:80"
#    volumes:
#      # NGinx static config file
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

#  traefik:
#    image: asn/traefik
#    build: traefik/
#    ports:
#      - "80:80"
#      - "8080:8080" # Web GUI
#    volumes:
#      # Traefik static config file
#      - ./traefik/traefik.yml:/etc/traefik/traefik.yml                                                                        
#      # Traefik provider config file
#      - ./traefik/dynamic-conf.yml:/etc/traefik/dynamic-conf.yml  

    depends_on:
      - wwwserver #LB should await for starting front-end server
  wwwserver:
    image: containous/whoami
    ports:
      # Random external port for HTTP direct access 
      - "80"
    # number of replicas
    scale: 2
    # limit resources for testing
    cpus: 1
    mem_limit: 128m
    mem_reservation: 64m
    oom_kill_disable: true #prevent stop containers when they reach their memory limit
